name: inventory_app
description: " Karam Stock - Inventory App"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.11
  google_mlkit_text_recognition: ^0.15.1
  image_picker: ^1.1.2
  image: ^4.1.7
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  excel: ^4.0.6
  share_plus: ^10.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"